name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build packages
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: 'windows-latest'
          CMD_BUILD: pyinstaller -F -w main.py
          OUT_FILE_NAME: main_windows
          OUT_FILE_PATH: dist/main.exe
        - os: 'ubuntu-latest'
          CMD_BUILD: pyinstaller -F -w main.py
          OUT_FILE_NAME: main_linux
          OUT_FILE_PATH: dist/main
        - os: 'macos-12'
          CMD_BUILD: >
              pyinstaller -w main.py &&
              cd dist/ &&
              tar -cvf main.tar main.app/
          OUT_FILE_NAME: main_macos
          OUT_FILE_PATH: dist/main.tar
        - os: 'macos-12'
          CMD_BUILD: >
              flet pack main.py &&
              cd dist/ &&
              tar -cvf main.tar main.app/
          OUT_FILE_NAME: main_macos2
          OUT_FILE_PATH: dist/main.tar
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - run: pip install flet chardet jinja2 pyinstaller
    - run: ${{ matrix.CMD_BUILD }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.OUT_FILE_NAME }}
        path: ${{ matrix.OUT_FILE_PATH }}
